apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
 name: creditizens-user-auth-consumer
 annotations:
   kubernetes.io/ingress.class: kong
# Username is a Kong cluster-unique username of the consumer but it is not important see it like a name, the most important is the credentials (secrets)
username: creditizens
credentials:
 - creditizens-nginx2-auth
